from src.seo_tools.schemas.analyze_keyword_rank import AnalyzeKeywordRankRequest, AnalyzeKeywordRankResult
from src.seo_tools.schemas.suggest_keywords import SuggestKeywordRequest, SuggestKeywordResult
from src.seo_tools.schemas.analyze_site_seo import AnalyzeSiteSeoRequest, AnalyzeSiteSeoResponse, CrawlMode