"""add_competitor_analysis_table

Revision ID: 20260514_235947
Revises: a1b2c3d4e5f6
Create Date: 2026-05-14 23:59:47.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260514_235947'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_analyses',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_url', sa.String(), nullable=False),
    sa.Column('competitor_url', sa.String(), nullable=False),
    sa.Column('crawl_mode', sa.Enum('QUICK', 'SITEMAP_ONLY', 'FULL_CRAWL', name='competitoranalysismode'), nullable=False),
    sa.Column('user_seo_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('competitor_seo_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('user_score', sa.Integer(), nullable=True),
    sa.Column('competitor_score', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Enum('USER', 'COMPETITOR', 'TIE', name='competitoranalysiswinner'), nullable=True),
    sa.Column('score_gap', sa.Integer(), nullable=True),
    sa.Column('comparison_report', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('suggestions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('quick_wins', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('strengths', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='competitoranalysisstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_analyses_competitor_url'), 'competitor_analyses', ['competitor_url'], unique=False)
    op.create_index(op.f('ix_competitor_analyses_user_id'), 'competitor_analyses', ['user_id'], unique=False)
    op.create_index(op.f('ix_competitor_analyses_user_url'), 'competitor_analyses', ['user_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_analyses_user_url'), table_name='competitor_analyses')
    op.drop_index(op.f('ix_competitor_analyses_user_id'), table_name='competitor_analyses')
    op.drop_index(op.f('ix_competitor_analyses_competitor_url'), table_name='competitor_analyses')
    op.drop_table('competitor_analyses')
    # ### end Alembic commands ###
