"""add_cicd_integration_tables

Revision ID: 47f04f0cbec8
Revises: add_status_column
Create Date: 2026-05-09 11:12:13.329035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47f04f0cbec8'
down_revision: Union[str, None] = 'add_status_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('webhook_configs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', 'GITLAB', name='webhookprovider'), nullable=False),
    sa.Column('repository_name', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=True),
    sa.Column('repository_owner', sa.String(), nullable=True),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('crawl_mode', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('events', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_configs_user_id'), 'webhook_configs', ['user_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('PULL_REQUEST', 'PUSH', 'MERGE_REQUEST', name='webhookeventtype'), nullable=False),
    sa.Column('delivery_id', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSING', 'COMPLETED', 'FAILED', name='webhookeventstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['webhook_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id')
    )
    op.create_index(op.f('ix_webhook_events_config_id'), 'webhook_events', ['config_id'], unique=False)
    op.create_table('pr_analyses',
    sa.Column('webhook_event_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_title', sa.String(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('repository_name', sa.String(), nullable=True),
    sa.Column('repository_owner', sa.String(), nullable=True),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('crawl_mode', sa.String(), nullable=False),
    sa.Column('seo_insight_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhook_event_id'], ['webhook_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pr_analyses_api_key_id'), 'pr_analyses', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_pr_analyses_job_id'), 'pr_analyses', ['job_id'], unique=False)
    op.create_index(op.f('ix_pr_analyses_user_id'), 'pr_analyses', ['user_id'], unique=False)
    op.create_index(op.f('ix_pr_analyses_webhook_event_id'), 'pr_analyses', ['webhook_event_id'], unique=False)
    op.add_column('seo_insight_results', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seo_insight_results', 'score')
    op.drop_index(op.f('ix_pr_analyses_webhook_event_id'), table_name='pr_analyses')
    op.drop_index(op.f('ix_pr_analyses_user_id'), table_name='pr_analyses')
    op.drop_index(op.f('ix_pr_analyses_job_id'), table_name='pr_analyses')
    op.drop_index(op.f('ix_pr_analyses_api_key_id'), table_name='pr_analyses')
    op.drop_table('pr_analyses')
    op.drop_index(op.f('ix_webhook_events_config_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_webhook_configs_user_id'), table_name='webhook_configs')
    op.drop_table('webhook_configs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###