"""initial

Revision ID: efe27befbe47
Revises: 
Create Date: 2026-03-26 08:48:20.292770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efe27befbe47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('keyword_rank_results',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('target_domain', sa.String(), nullable=True),
    sa.Column('target_position', sa.Integer(), nullable=True),
    sa.Column('total_results', sa.Integer(), nullable=False),
    sa.Column('search_results', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_rank_results_keyword'), 'keyword_rank_results', ['keyword'], unique=False)
    op.create_index(op.f('ix_keyword_rank_results_target_url'), 'keyword_rank_results', ['target_url'], unique=False)
    op.create_index(op.f('ix_keyword_rank_results_user_id'), 'keyword_rank_results', ['user_id'], unique=False)
    op.create_table('keyword_suggestions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('primary_keyword', sa.String(), nullable=False),
    sa.Column('search_results', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('related_searches', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('people_also_ask', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('autocomplete_suggestions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('long_tail_keywords', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('total_related_terms', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_suggestions_primary_keyword'), 'keyword_suggestions', ['primary_keyword'], unique=False)
    op.create_index(op.f('ix_keyword_suggestions_user_id'), 'keyword_suggestions', ['user_id'], unique=False)
    op.create_table('seo_insight_results',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('crawl_mode', sa.String(), nullable=False),
    sa.Column('base_url_checks', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('url_results', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_insight_results_target_url'), 'seo_insight_results', ['target_url'], unique=False)
    op.create_index(op.f('ix_seo_insight_results_user_id'), 'seo_insight_results', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_insight_results_user_id'), table_name='seo_insight_results')
    op.drop_index(op.f('ix_seo_insight_results_target_url'), table_name='seo_insight_results')
    op.drop_table('seo_insight_results')
    op.drop_index(op.f('ix_keyword_suggestions_user_id'), table_name='keyword_suggestions')
    op.drop_index(op.f('ix_keyword_suggestions_primary_keyword'), table_name='keyword_suggestions')
    op.drop_table('keyword_suggestions')
    op.drop_index(op.f('ix_keyword_rank_results_user_id'), table_name='keyword_rank_results')
    op.drop_index(op.f('ix_keyword_rank_results_target_url'), table_name='keyword_rank_results')
    op.drop_index(op.f('ix_keyword_rank_results_keyword'), table_name='keyword_rank_results')
    op.drop_table('keyword_rank_results')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###